---
title: "How to use the lifelihood package"
author: "Nicolas RODE, Thomas LENORMAND"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: journal
    css: style.css
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
editor_options: 
  chunk_output_type: console
---

<br>

# Load libraries
***

```{r}
library(lifelihood)
```

<br>

# Data preparation
***

Load the dataset from `.csv` file:

```{r}
# input data
df <- read.csv(here::here('data/fake_sample.csv'))
kableExtra::kable(df)
```

Prepare input parameters for the `lifelihood()` function:

```{r}
# we define name of the columns of the clutchs into a single vector
clutchs = c(
   'clutch_start1', 'clutch_end1', 'clutch_size1',
   'clutch_start2', 'clutch_end2', 'clutch_size2',
   'clutch_start3', 'clutch_end3', 'clutch_size3'
)
```

<br>

# Get the results
***

## All default parameters

```{r}
# run the analysis
results <- lifelihood(
  df = df,
  sex = 'sex',
  sex_start = 'sex_start',
  sex_end = 'sex_end',
  maturity_start = 'mat_start',
  maturity_end = 'mat_end',
  clutchs = clutchs,
  death_start = 'mor_start',
  death_end = 'mor_end',
  extra1 = 'geno'
)
summary(results)
```

## With custom parameter ranges

```{r}
# dataframe with param ranges
param_ranges <- data.frame(
  param = c("E(tmort)f", "morta", "RE(tmort)m", "mortp", "propmal", "E(tmat)f", "mata", 
            "RE(tmat)m", "E(tpon)", "ponta", "pontn", "to(ps)int", "to(ps)am", "to(ps)tp", 
            "sen(pu)t", "sen(pu)t2", "sen(pn)t", "sen(pn)t2", "to(pupn)", "W"),
  min = c(1, 0.001, 0.1, 0.0001, 0.00001, 1, 0.0001, 0.1, 0.1, 0.001, 1, 0.00001, 
          0.0000001, 0.0000001, -20, -20, -8, -8, -8, 0.001),
  max = c(300, 20, 4, 1, 0.99999, 100, 15, 10, 200, 12, 50, 10, 10, 10, 20, 20, 10, 10, 10, 1200)
)
kableExtra::kable(param_ranges)

# run the analysis
results <- lifelihood(data_path=path_to_data, param_range_df=param_ranges)
summary(results)
```