---
title: "Reproduction survival tradeoff"
vignette: >
  %\VignetteIndexEntry{reproduction-survival-tradeoff}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
code-annotations: hover
execute: 
  cache: true
embed-resources: true
---



# Load libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options("digits" = 10)
```

# Analysis
```{r}
library(lifelihood)
library(tidyverse)

df <- datapierrick |>
  as_tibble() |>
  mutate(
    par = as.factor(par),
    geno = as.factor(geno),
    spore = as.factor(spore)
  ) |>
  filter(par == "0")

df |>
  group_by(geno) |>
  summarise(longevity = mean((death_start + death_end) / 2))

generate_clutch_vector <- function(N) {
  return(paste(
    "clutch",
    rep(c("start", "end", "size"), N),
    rep(1:N, each = 3),
    sep = "_"
  ))
}
clutchs <- generate_clutch_vector(28)

lifelihoodData <- as_lifelihoodData(
  df = df,
  sex = "sex",
  sex_start = "sex_start",
  sex_end = "sex_end",
  maturity_start = "mat_start",
  maturity_end = "mat_end",
  clutchs = clutchs,
  death_start = "death_start",
  death_end = "death_end",
  matclutch = FALSE,
  covariates = c("par", "geno"),
  dist = c("wei", "gam", "lgn")
)

## Right convergence
m1 <- lifelihood(
  lifelihoodData = lifelihoodData,
  path_config = use_test_config("config_pierrick_geno_death"),
  raise_estimation_warning = FALSE,
  delete_temp_files = FALSE,
  seed = c(2054, 9713, 3767, 8573),
  #  n_fit=10
)

AICc(m1)

summary(m1)

# Prediction
newdata <- data.frame(geno = 0:3)
newdata$geno <- factor(newdata$geno)

prediction(m1, "expt_death", newdata = newdata, type = "response")

plot_fitted_event_rate(
  m1,
  interval_width = 5,
  event = "mortality",
  use_facet = TRUE,
  groupby = "geno",
  xlab = "Age (days)",
  ylab = "Fitted Mortality Rate",
)
```

# Simulations
## From Lifelihood results
```{r}
simulate_life_history(m1, event = "mortality") |>
  mutate(geno = df$geno) |>
  group_by(geno) |>
  summarise(longevity = mean((death_start + death_end) / 2))
```

## From scratch without tradeoffs
```{r }
population <- crossing(
  geno = as.factor(0:3),
  sex = 0
) |>
  mutate(n_individuals = 100)


## Define model to simulate
simulation_config <- list(
  mortality = list(
    expt_death = "geno",
    survival_param2 = 1,
    ratio_expt_death = "not_fitted",
    prob_death = "not_fitted",
    sex_ratio = "not_fitted"
  ),
  maturity = list(
    expt_maturity = 1,
    maturity_param2 = 1,
    ratio_expt_maturity = "not_fitted"
  ),
  reproduction = list(
    expt_reproduction = 1,
    reproduction_param2 = 1,
    n_offspring = 1,
    increase_death_hazard = "not_fitted",
    tof_decay = "not_fitted",
    increase_death_hazard_n_offspring = "not_fitted",
    lin_decrease_hazard = "not_fitted",
    quad_decrease_hazard = "not_fitted",
    lin_change_n_offspring = "not_fitted",
    quad_change_n_offspring = "not_fitted",
    tof_n_offspring = "not_fitted",
    fitness = "not_fitted"
  )
)

## Define effects
effects <- list(
  expt_death = list(intercept = coef(m1)[1], geno = coef(m1)[2:4]),
  survival_param2 = coef(m1)[5],
  expt_maturity = coef(m1)[6],
  maturity_param2 = coef(m1)[7],
  expt_reproduction = coef(m1)[8],
  reproduction_param2 = coef(m1)[9],
  n_offspring = coef(m1)[10]
)

## Inputs with distributions
simulation_input <- create_simulation_input(
  effects = effects,
  data = population,
  covariates = c("geno"),
  sex = "sex",
  matclutch =TRUE,
  matclutch_size="first_clutch_size",
  block="block",
  config = simulation_config,
  dist = c("wei", "gam", "lgn"),
  n_per_combination = "n_individuals",
  param_bounds_df=m1$param_bounds_df
)

## Add block to dataset
simulation_input$lifelihoodData$df <- data.frame(block = rep(1, nrow(simulation_input$lifelihoodData$df)), simulation_input$lifelihoodData$df)

visits <- data.frame(block = 1, visit = seq(1, 200, by=0.1))

sim_data <- simulate_life_history(object = simulation_input,
                                  event = "all",
                                  use_censoring = TRUE,
                                  visits = visits)
sim_data

sim_data |>
  mutate(geno=simulation_input$lifelihoodData$df$geno)|>
  group_by(geno)|>
  summarise(longevity=mean((mortality_start+mortality_end)/2))


```


## From scratch with tradeoffs
```{r }
population <- crossing(
  geno = as.factor(0:3),
  sex = 0
) |>
  mutate(n_individuals = 5)

## Define model to simulate
simulation_config <- list(
  mortality = list(
    expt_death = "geno",
    survival_param2 = 1,
    ratio_expt_death = "not_fitted",
    prob_death = "not_fitted",
    sex_ratio = "not_fitted"
  ),
  maturity = list(
    expt_maturity = 1,
    maturity_param2 = 1,
    ratio_expt_maturity = "not_fitted"
  ),
  reproduction = list(
    expt_reproduction = 1,
    reproduction_param2 = 1,
    n_offspring = 1,
    increase_death_hazard = 1,
    tof_decay = "not_fitted",
    increase_death_hazard_n_offspring = "not_fitted",
    lin_decrease_hazard = "not_fitted",
    quad_decrease_hazard = "not_fitted",
    lin_change_n_offspring = "not_fitted",
    quad_change_n_offspring = "not_fitted",
    tof_n_offspring = "not_fitted",
    fitness = "not_fitted"
  )
)

## Define effects
effects <- list(
  expt_death = list(intercept = coef(m1)[1], geno = coef(m1)[2:4]),
  survival_param2 = coef(m1)[5],
  increase_death_hazard = -10,
  expt_maturity = coef(m1)[6],
  maturity_param2 = coef(m1)[7],
  expt_reproduction = coef(m1)[8],
  reproduction_param2 = coef(m1)[9],
  n_offspring = coef(m1)[10]
)

## Inputs with distributions
simulation_input <- create_simulation_input(
  effects = effects,
  data = population,
  covariates = c("geno"),
  sex = "sex",
  matclutch =FALSE,
  matclutch_size="first_clutch_size",
  block="block",
  config = simulation_config,
  dist = c("wei", "gam", "lgn"),
  n_per_combination = "n_individuals",
  param_bounds_df=m1$param_bounds_df
)

## Add block to dataset
simulation_input$lifelihoodData$df <- data.frame(block=rep(1, nrow(simulation_input$lifelihoodData$df)), simulation_input$lifelihoodData$df)

visits <- data.frame(block = 1, visit = seq(1, 200, by = 0.1))
set.seed(123)
sim_data <- simulate_life_history(object = simulation_input,
                                  event = "all",
                                  use_censoring = FALSE)
                                  #visits = visits)

sim_data
colnames(sim_data)

## Remove LRS
sim_data <- sim_data |>
  select(-total_n_offspring)

```

# Analyse simulations
```{r }

sim_data|>
  group_by(geno)|>
  summarise(longevity=mean((death_start+death_end)/2))

sim_data|>
#mutate(toto=death_start-maturity_start)|>
#mutate(toto=clutch_start_1-maturity_start)|>
mutate(toto=death_start-clutch_start_19)|>
 summarize(min(toto, na.rm = TRUE))

generate_clutch_vector <- function(N) {
  return(paste(
    "clutch",
    rep(c("start", "end", "size"), N),
    rep(1:N, each = 3),
    sep = "_"
  ))
}
clutchs <- generate_clutch_vector(19)

lifelihoodData <- as_lifelihoodData(
  df = sim_data,
  sex = "sex",
  sex_start = "sex_start",
  sex_end = "sex_end",
  maturity_start = "maturity_start",
  maturity_end = "maturity_end",
  clutchs = clutchs,
  death_start = "death_start",
  death_end = "death_end",
  matclutch = FALSE,
  covariates = c("geno"),
  dist = c("wei", "gam", "lgn")
)

## Right convergence
m1 <- lifelihood(
 lifelihoodData = lifelihoodData,
path_config = use_test_config("config_pierrick_geno_death"),
raise_estimation_warning = FALSE,
delete_temp_files = FALSE,
seed=c(2054, 9713, 3767, 8573),
sub_interval = 0.05
 #n_fit=10
)

#AICc(m1)

```