---
title: "What is the required data format?"
author: "Nicolas RODE, Thomas LENORMAND"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    theme: journal
    css: style.css
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
editor_options: 
  chunk_output_type: console
---

<br>

# Introduction
***

As life history data is by nature heterogeneous between observations from the same sample, the format of the data required can be somewhat tricky. Under the hood, `lifelihood` creates a text file containing the data (and other parameters), and then use this file for the (core) source code. Fortunately, `lifelihood` automatically transform the dataframe into the text file with the right format.

In this vignette, we'll look at how the dataframe containing your data needs to be formatted for the Lifelihood programme to work properly.

# Data preparation
***

But in order for this to work properly, it requires a specific format.

Let's create a simple dataset with just 7 observations:

- `geno` is a simple categorical variable
- `sex` is a (pseudo-) boolean of 0 and 1
- `mat_start` and `mat_end` designate the interval where the maturity occured
- `pon_start1` and `pon_end1` designate the interval of the 1st pont
- `pon_start2` and `pon_end2` designate the interval of the 2nd pont
- etc for other potential ponts
- `mor_start` and `mor_end` designate the interval where the death occured

```{r}
df <- data.frame(
  geno = c(1, 2, 1, 0, 2, 0, 1),
  sex = c(0, 0, 0, 0, 0, 0, 0),
  mat_start = c(2, 1, 0, 1, 0, 2, 1),
  mat_end = c(3, 2, 1000, 2, 1000, 3, 2),
  pon_start1 = c(3, 2, NA, 2, NA, 3, 2),
  pon_end1 = c(4, 3, NA, 3, NA, 4, 3),
  pon_size1 = c(4, 6, NA, 5, NA, 2, 7),
  pon_start2 = c(5, NA, NA, 5, NA, 4, 3),
  pon_end2 = c(6, NA, NA, 6, NA, 5, 4),
  pon_size2 = c(5, NA, NA, 5, NA, 3, 5),
  pon_start3 = c(7, NA, NA, 6, NA, NA, 5),
  pon_end3 = c(8, NA, NA, 7, NA, NA, 6),
  pon_size3 = c(1, NA, NA, 1, NA, NA, 2),
  mor_start = c(8, 11, 0, 11, 0, 7, 9),
  mor_end = c(9, 12, 1, 12, 1, 8, 10)
)
kableExtra::kable(df)
```

As you can see, some observations made more ponts, leading to the presence of NULL values.

*One* row of the dataset should represent the **life history** of *one* observation.

TODO: finish this vignette