---
title: "Lifelihood analyses"
author: "Nicolas RODE, Thomas LENORMAND"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document: 
    number_sections: yes
    theme: journal
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
editor_options: 
  chunk_output_type: console
---

```{r setup, include =FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
devtools::load_all() 
```
# Analyses
## Test LifelihoodC
```{r, eval=FALSE }
pathtolifelihood <- here::here("src/lifelihoodC.exe")
infile=here::here("data/raw_data/100%mort_Pierrickintercept.txt")
customfile=here::here("data/raw_data/custom.txt")

pathtolifelihood <- gsub("/","\\", pathtolifelihood , fixed=T)
infile <- gsub("/","\\", infile, fixed=T)
customfile <- gsub("/","\\", customfile, fixed=T)

GbyG=0
MCMC=0
interval=25
SEcal="false"
saveprobevent=0
fitness=0
r=0
seed1=12
seed2=13
seed3=14
seed4=15
ntr=2
nst=2
To=50
Tf=1
climbrate=1
precision=0.001
string <- paste(infile, customfile, GbyG, MCMC, interval, SEcal, saveprobevent, fitness, r, seed1, seed2, seed3, seed4, ntr, nst, To, Tf, climbrate, precision)
  
system(pathtolifelihood, intern = FALSE,
         ignore.stdout = FALSE, ignore.stderr = FALSE,
         wait = TRUE, input = string, show.output.on.console = TRUE,
         minimized = FALSE, invisible = TRUE)

```