---
title: "Mortality rate visualization"
output: 
  html_document:
    theme: journal
    toc: yes
    toc_float:
      collapsed: no
editor_options: 
  chunk_output_type: console
---

# Load libraries
***

```{r}
# library(lifelihood)
devtools::load_all(compile = FALSE)
```

# Data preparation
***

```{r}
df <- read.csv(here::here("data/raw_data/DataPierrick/100%mort_Pierrick211genoparinteraction.csv"))
df$geno <- as.factor(df$geno)
df$par <- as.factor(df$par)
df$spore <- as.factor(df$spore)

generate_clutch_vector <- function(N) {
  return(paste("pon", rep(c("start", "end", "size"), N), rep(1:N, each = 3), sep = "_"))
}
clutchs <- generate_clutch_vector(28)

dataLFH <- lifelihoodData(
  df = df,
  sex = "sex",
  sex_start = "sex_start",
  sex_end = "sex_end",
  maturity_start = "mat_start",
  maturity_end = "mat_end",
  clutchs = clutchs,
  death_start = "mor_start",
  death_end = "mor_end",
  covariates = c("par", "geno", "spore"),
  model_specs = c("wei", "lgn", "wei")
)
```

# Plot mortality rate

```{r}
plot_mortality_rate(dataLFH, interval_width = 20, max_time = 170, log_y = TRUE)
```

# Get mortality rate

```{r}
mort_df <- mortality_rate(dataLFH, interval_width = 5)
head(mort_df)
```