#' @title Display evolution of empirical mortality rate
#' @description Useful function for creating a good-quality line graph of changes in the empirical mortality rate.
#' @name plot_mortality_rate
#' @inheritParams lifelihood
#' @inheritParams check_valid_estimation
#' @inheritParams mortality_rate
#' @inheritParams predict
#' @param prediction Decide whether the plotted mortality rate should be based on empirical data using [lifelihoodData()] or on predicted values generated by [lifelihoodResults()] (and [predict()], under the bonnet). If `newdata` is `NULL`, predictions are made for the subjects included in the original model fit.
#' @param log_x Determine whether the x-axis should be displayed on a logarithmic scale.
#' @param log_y Determine whether the y-axis should be displayed on a logarithmic scale.
#' @details This function requires [ggplot2](https://ggplot2.tidyverse.org/) to be installed.
#' @return none
#' @examples
#' df <- read.csv(here::here("data/raw_data/DataPierrick/100%mort_Pierrick211genoparinteraction.csv"))
#' df$geno <- as.factor(df$geno)
#' df$par <- as.factor(df$par)
#' df$spore <- as.factor(df$spore)
#' clutchs <- paste("pon", rep(c("start", "end", "size"), 28), rep(1:28, each = 3), sep = "_")
#'
#' dataLFH <- lifelihoodData(
#'   df = df,
#'   sex = "sex",
#'   sex_start = "sex_start",
#'   sex_end = "sex_end",
#'   maturity_start = "mat_start",
#'   maturity_end = "mat_end",
#'   clutchs = clutchs,
#'   death_start = "death_start",
#'   death_end = "death_end",
#'   covariates = c("par", "geno", "spore"),
#'   model_specs = c("gam", "lgn", "wei")
#' )
#'
#' plot_mortality_rate(dataLFH, interval_width = 20, max_time = 170)
#' plot_mortality_rate(
#'   dataLFH,
#'   interval_width = 10,
#'   max_time = 170,
#'   bygroup = FALSE,
#'   log_y = TRUE
#' )
#' @export
plot_mortality_rate <- function(
  interval_width,
  lifelihoodData = NULL,
  lifelihoodResults = NULL,
  prediction = FALSE,
  newdata = NULL,
  max_time = NULL,
  bygroup = TRUE,
  log_x = FALSE,
  log_y = FALSE
) {
  if (prediction) {
    if (is.null(lifelihoodResults)) {
      stop("`lifelihoodResults` cannot be `NULL` when `prediction` is `TRUE`.")
    }
    if (!is.null(lifelihoodData)) {
      warning(
        "`lifelihoodData` argument is ignored when `prediction` is `TRUE`."
      )
    }
    rate_df <- pred_mortality_rate(
      lifelihoodResults,
      interval_width,
      newdata = newdata,
      max_time = max_time,
      bygroup = bygroup
    )
  } else {
    if (is.null(lifelihoodData)) {
      stop("`lifelihoodData` cannot be `NULL` when `prediction` is `FALSE`.")
    }
    if (!is.null(lifelihoodResults)) {
      warning(
        "`lifelihoodResults` argument is ignored when `prediction` is `FALSE`."
      )
    }
    rate_df <- mortality_rate(
      lifelihoodData,
      interval_width,
      max_time = max_time,
      bygroup = bygroup
    )
  }

  if (bygroup) {
    plot <- ggplot2::ggplot(
      rate_df,
      ggplot2::aes(
        x = as.numeric(as.character(Interval)),
        y = MortalityRate,
        color = Group
      )
    )
  } else {
    plot <- ggplot2::ggplot(
      rate_df,
      ggplot2::aes(x = as.numeric(as.character(Interval)), y = MortalityRate)
    )
  }

  plot <- plot +
    ggplot2::geom_line() +
    ggplot2::labs(
      title = "Mortality Rate Over Time",
      x = "Time",
      y = "Mortality Rate"
    ) +
    ggplot2::theme_minimal()

  if (!is.null(max_time) & !log_x) {
    plot <- plot + ggplot2::xlim(0, max_time)
  }

  if (log_x) {
    plot <- plot + ggplot2::scale_x_log10()
  }
  if (log_y) {
    plot <- plot + ggplot2::scale_y_log10()
  }

  plot
}
