name: Deploy Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-docs:
    runs-on: macos-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          brew install pandoc

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build pkgdown site
        run: |
          Rscript -e 'install.packages(c("devtools", "tidyverse", "quarto"))'
          Rscript -e 'pkgdown::build_site()'

      - name: Deploy to gh-pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
